### ISSUE TITLE
Readme: Improve development / deliverable instructions

### ISSUE THREAD

**Issue by coreyshuman** [Shift3/react-challenge-project#35]
From the project README:

`
Once you have created your fork, review the Issues labeled challenge task HERE. Work on each task in a new branch. Once the work is completed, create a Pull Request from the working branch to your master branch and reference the Issue you are working on. These open PRs will be the final submission which Shift3 will review.
`

The wording in this is confusing. At face value, it does not appear to follow our branching and PR standards.

This should be reworded to more clearly follow the pattern:

**feature branch -> PR -> development branch**

and once all features are completed:

**development branch -> PR -> master branch**

We should also mention that both the closed feature PRs and the open dev->master PR will be reviewed.

**Comment by coreyshuman** [comment]
@Shift3/pr-team Does anyone have the bandwidth to address this right away?

**Comment by kmausolf** [comment]
Resolved by #36
